hollymovies/urls.py
from django.contrib import admin
from django.urls import include, path

from viewer.models import Genre, Movie
from viewer.views import IndexView

admin.site.register(Genre)
admin.site.register(Movie)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('viewer/', include('viewer.urls', namespace='viewer'))
]

viewer/urls.py
from django.urls import path

from viewer.views import (
    IndexView, MovieCreateView, MovieDeleteView, MovieDetailView,
    MovieListView, MovieUpdateView
)

app_name = 'viewer'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('movie/list', MovieListView.as_view(), name='movie_list'),
    path('movie/detail/<pk>', MovieDetailView.as_view(), name='movie_detail'),
    path('movie/create', MovieCreateView.as_view(), name='movie_create'),
    path('movie/update/<pk>', MovieUpdateView.as_view(), name='movie_update'),
    path('movie/delete/<pk>', MovieDeleteView.as_view(), name='movie_delete')
]

viewer/models.py
from django.db.models import (
    DO_NOTHING, CharField, DateField, DateTimeField, ForeignKey, IntegerField,
    Model, TextField
)


class Genre(Model):

    name = CharField(max_length=128)

    def __str__(self):
        return self.name


class Movie(Model):

    title = CharField(max_length=128)
    genre = ForeignKey(Genre, on_delete=DO_NOTHING)
    rating = IntegerField()
    released = DateField()
    description = TextField(null=True, blank=True)
    created = DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

viewer/forms.py
import re
from datetime import date

from django.core.exceptions import ValidationError
from django.forms import CharField, DateField, IntegerField, ModelForm

from viewer.models import Movie


def capitalized_validator(value):
    if value[0].islower():
        raise ValidationError('Value must be capitalized.')


class PastMonthField(DateField):

    def validate(self, value):
        super().validate(value)
        if value >= date.today():
            raise ValidationError('Only past dates allowed here.')

    def clean(self, value):
        result = super().clean(value)
        return date(year=result.year, month=result.month, day=1)


class MovieForm(ModelForm):

    class Meta:
        model = Movie
        fields = '__all__'

    title = CharField(validators=[capitalized_validator])
    rating = IntegerField(min_value=1, max_value=10)
    released = PastMonthField()

    def clean_description(self):
        # Force each sentence of the description to be capitalized.
        initial = self.cleaned_data['description']
        sentences = re.sub(r'\s*\.\s*', '.', initial).split('.')
        return '. '.join(sentence.capitalize() for sentence in sentences)

    def clean(self):
        result = super().clean()
        if result['genre'].name == 'Comedy' and result['rating'] > 5:
            self.add_error('genre', '')
            self.add_error('rating', '')
            raise ValidationError(
                "Comedies aren't so good to be rated over 5."
            )
        return result

viewer/views.py
from logging import getLogger

from django.urls import reverse_lazy
from django.views.generic import (
    CreateView, DeleteView, DetailView, ListView, UpdateView
)

from viewer.forms import MovieForm
from viewer.models import Movie

LOGGER = getLogger()


class MovieListView(ListView):
    template_name = 'movie_list.html'
    model = Movie


class MovieDetailView(DetailView):
    template_name = 'movie_detail.html'
    model = Movie


class MovieCreateView(CreateView):
    template_name = 'form.html'
    form_class = MovieForm
    success_url = reverse_lazy('viewer:movie_list')


class MovieUpdateView(UpdateView):
    template_name = 'form.html'
    model = Movie
    form_class = MovieForm
    success_url = reverse_lazy('viewer:movie_list')


class MovieDeleteView(DeleteView):
    template_name = 'movie_confirm_delete.html'
    model = Movie
    success_url = reverse_lazy('viewer:movie_list')


class IndexView(MovieListView):
    template_name = 'index.html'

viewer/templates/base.html
{% load bootstrap4 %}
{% load static %}

<html {% if LANGUAGE_CODE %}lang="{{ LANGUAGE_CODE }}"{% endif %}>

  <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <title>HollyMovies</title>
      {% block styles %}{% bootstrap_css %}{% endblock %}
      {% block scripts %}{% bootstrap_javascript jquery='full' %}{% endblock %}
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container fixed">
        <a class="navbar-brand" href="{% url 'index' %}">HollyMovies</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-item nav-link active" href="{% url 'index' %}">
              Home
            </a>
            <div class="nav-item dropdown">
              <a class="nav-link active dropdown-toggle" href="#" data-toggle="dropdown">
                Movies
              </a>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'viewer:movie_list' %}">List</a>
                <a class="dropdown-item" href="{% url 'viewer:movie_create' %}">Create</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </nav>
    <div class="container">
      <div class="jumbotron">
        {% block content %}{% endblock %}
      </div>
    </div>
  </body>

</html>

viewer/templates/form.html
{% extends "base.html" %}

{% load bootstrap4 %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <input type="submit" value="Submit" class="btn btn-primary">
    {% endbuttons %}
  </form>
{% endblock %}

viewer/templates/index.html
{% extends "base.html" %}

{% load movie_extras %}

{% block content %}
  <h1>Welcome to HollyMovies!</h1>
  <ul>
    {% for movie in object_list %}
      <li>{% movie_format movie %}</li>
    {% endfor %}
  </ul>
{% endblock %}

viewer/templates/movie_confirm_delete.html
{% extends "base.html" %}

{% load bootstrap4 %}

{% block content %}
  <form method="post">
    {% csrf_token %} 
    <p>
      Are you sure you want to delete movie "{{ object.title }}" from database?
    </p> 
    <input type="submit" value="Submit" class="btn btn-danger">
  </form> 
{% endblock %}

viewer/templates/movie_detail.html
{% extends "base.html" %}

{% load movie_extras %}

{% block content %}
  {{ movie|attr_as_p:'title' }}
  {{ movie|attr_as_p:'released' }}
  {{ movie|attr_as_p:'genre' }}
  {{ movie|attr_as_p:'rating' }}
  {{ movie|attr_as_p:'description' }}
{% endblock %}

viewer/templates/movie_list.html
{% extends "base.html" %}

{% load movie_extras %}

{% block content %}
  <ul>
    {% for movie in object_list %}
      <li>
        {% movie_format movie short=True %}
        <a href="{% url 'viewer:movie_detail' movie.pk %}">detail</a> /
        <a href="{% url 'viewer:movie_update' movie.pk %}">update</a> /
        <a href="{% url 'viewer:movie_delete' movie.pk %}">delete</a>
      </li>
    {% endfor %}
  </ul>
{% endblock %}